kind: ConfigMap
metadata:  
  name: core-dns-service-coredns
  namespace: dns-service
apiVersion: v1
data:
  Corefile: |-
    .:53 {
        errors
        health {
            lameduck 10s
        }
        hosts {
            192.168.203.70 www.syargocd.com
            192.168.203.63 www.syansible.com
            192.168.202.70 www.syk8smaster.com
            192.168.202.72 www.syk8snode1.com
            192.168.202.78 www.sydockerbuilder.com
            192.168.203.64 www.sygrafana.com
            192.168.203.67 www.syprometheus.com
            fallthrough 
        }
        ready
        kubernetes cluster.local in-addr.arpa ip6.arpa {
            pods insecure
            fallthrough in-addr.arpa ip6.arpa
            ttl 30
        }
        prometheus 0.0.0.0:9153
        forward . /etc/resolv.conf
        cache 30
        loop
        reload
        loadbalance
    }
