kind: ConfigMap
metadata:  
  name: core-dns-service-coredns
  namespace: dns-service
apiVersion: v1
data:
  Corefile: |-
    .:53 {
        errors
        health {
            lameduck 10s
        }
        hosts {
            192.168.203.63 www.syargocd.com
            192.168.202.20 www.mycvp.com 
            192.168.203.20 www.game.com 
            192.168.202.21 www.mycvp1.com
            192.168.202.22 www.mycvp2.com
            192.168.202.23 www.mycvp3.com
            192.168.202.243 www.mycvp4.com
            fallthrough 
        }
        ready
        kubernetes cluster.local in-addr.arpa ip6.arpa {
            pods insecure
            fallthrough in-addr.arpa ip6.arpa
            ttl 30
        }
        prometheus 0.0.0.0:9153
        forward . /etc/resolv.conf
        cache 30
        loop
        reload
        loadbalance
    }
